### ISSUE TITLE
add spec for layout

### ISSUE THREAD

**Issue by larrybotha** [fixate/kss-boilerplate#1]
@robguy21

layout should include template for island objects, where padding of islands is highlighted to differentiate it from content

following can be used in layout.css to highlight padding but no content:

``` css
[class*="island"] { background-color: hotpink;}
[class*="island"] * { background-color: #FFF;}
```
